#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"
DOTFILES_ROOT=$(pwd -P)
source $DOTFILES_ROOT/functions/log
loglevel=1

# Run Homebrew through the Brewfile
info "› brew bundle"
brew bundle

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
